codemaker: write version 49 (1.5) class files
The trick of writing generic types into class files of versions < 49
does no longer work with javac from OpenJDK 7:

/comphelper/qa/complex/comphelper/Map.java:154: error: type Pair does
not take parameters
  Pair< ?, ? >[] initialMappings = new Pair< ?, ? >[ _keys.length ];

There appears to be a related JDK bug for this, at some time javac had
an undocumented option to produce similar class files that are also
rejected now, this has been closed as "Not a Defect":

http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7078419

Change-Id: I8a504f6cbb3bb58cd914aebb88637cc6feb0bd48
(cherry picked from commit 26643fb59e0005f0bc83708b785d20d62d8e7411)

Signed-off-by: Michael Stahl <mstahl@redhat.com>
Signed-off-by: Stephan Bergmann <sbergman@redhat.com>

Gbp-Pq: Name jdk7.diff